FROM alpine:3.15

RUN mkdir /gameHeroes

COPY . /gameHeroes

RUN apk update &&\

    # Install wine and Python
    apk add --no-cache wine &&\
    wget https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tgz &&\
    tar -xvzf Python-3.8.13.tgz &&\
    wine msiexec /i python-3.8.13.amd64.msi /qb &&\

    # Install PyInstaller on wine
    cd ~/.wine/drive_c/Python38 &&\
    wine python.exe Scripts/pip.exe install -r /gameHeroes/requirements.txt &&\

    # Package a python scripts
    wine ~/.wine/drive_c/Python38/Scripts/pyinstaller.exe -F -w /gameHeroes/main.py &&\

CMD ["wine","dist/main.exe"]
